# ====================================================================
#              Automated Audit of Latest Workflow Commit
#
# This version has been corrected to use job-level environment
# variables for better scoping and clarity, as requested.
# ====================================================================

name: "Automated Audit: Extract Latest Recon Data"

on:
  workflow_run:
    workflows: ["permutate.yml"]
    types:
      - completed
      
  workflow_dispatch:
      

jobs:
  extract_latest_commit_data:
    # Only run if the triggering workflow was a success.
    #if: github.event.workflow_run.conclusion == 'success'
    
    name: Extract Data From Latest Commit
    runs-on: ubuntu-latest
    env:
      STORE_OWNER: ${{ secrets.SECONDRY_USERNAME }}
      STORE_REPO_NAME: ${{ secrets.STORE }}
      STORE_TOKEN: ${{ secrets.PAT_FOR_SECONDRY }}

    steps:
      # Step 1: Checkout the private 'store-recon' repository.
      # This step correctly uses the job-level environment variables.
      - name: Checkout the private store-recon repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.STORE_OWNER }}/${{ env.STORE_REPO_NAME }}
          token: ${{ env.STORE_TOKEN }}
          fetch-depth: 0

      # Step 2: Find the single most recent commit and extract its data.
      # Step 2: Find the single most recent commit and extract its data
      - name: Extract New Entries via git show
        shell: bash
        run: |
          
          PATTERN="feat: Add new assets from distributed permutation scan"

          # Block 1: Find the target commit hash
          echo "::group::[DEBUG] Block 1: Finding Commit"
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            COMMIT="${{ github.event.workflow_run.head_sha }}"
            echo "▶️ Trigger is 'workflow_run'. Inspecting commit: $COMMIT"
            git fetch --no-tags origin "$COMMIT"
          else
            echo "▶️ Trigger is 'workflow_dispatch'. Finding latest commit with pattern: '$PATTERN'"
            COMMIT=$(git log --no-merges --grep="$PATTERN" -n1 --format="%H")
            if [ -z "$COMMIT" ]; then
              echo "::error::No commit found matching '$PATTERN'"
              exit 1
            fi
            echo "   → Found commit: $COMMIT"
          fi
          echo "::endgroup::"


          # Block 2: Show full details of the commit found
          echo "::group::[DEBUG] Block 2: Verifying Commit Details"
          echo "Showing details for commit $COMMIT..."
          git log -n1 --pretty=fuller "$COMMIT"
          echo "::endgroup::"


          # Block 3: Show the raw diff output from git
          # This is the most important debug step. It shows what `grep` will receive.
          echo "::group::[DEBUG] Block 3: Raw 'git show' Output"
          echo "Showing raw, unfiltered diff for $COMMIT. The next grep command will process this output."
          # We use `|| true` in case a commit has no diff (e.g., first commit) to avoid exiting.
          git show "$COMMIT" --unified=0 || true
          echo "End of raw 'git show' output."
          echo "::endgroup::"
          

          # Block 4: Run the extraction command and show the result
          echo "::group::[DEBUG] Block 4: Filtering Diff and Creating File"
          echo "Filtering raw diff for lines starting with '+' and creating 'latest_entries.txt'..."
          git show "$COMMIT" --unified=0 \
            | grep '^\+' \
            | grep -v '^\+\+\+' \
            > latest_entries.txt || true
          echo "File 'latest_entries.txt' created."
          echo "--- Contents of latest_entries.txt ---"
          cat latest_entries.txt
          echo "--- End of file contents ---"
          echo "::endgroup::"


          # Block 5: Count the lines and validate
          echo "::group::[DEBUG] Block 5: Final Validation"
          COUNT=$(wc -l < latest_entries.txt)
          echo "Line count in latest_entries.txt is: $COUNT"
          if [ "$COUNT" -eq 0 ]; then
            echo "::error::No added lines were found after filtering the diff from commit $COMMIT."
            exit 1
          fi
          echo "Validation successful."
          echo "::endgroup::"


          echo "✅ Found $COUNT new entries in $COMMIT"
          echo "Total new entries found: $(wc -l < latest_entries.txt)"

    

          #git show -m "$LATEST_COMMIT_HASH" | grep '^\+' | grep -v '^\+\+\+' > latest_entries.txt || true

      # Step 3: Upload the extracted data as a downloadable artifact.
      - name: Upload Latest Entries as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "new-entries-from-run-${{ github.event.workflow_run.id }}"
          path: latest_entries.txt
          retention-days: 1
